#!/bin/sh
# Compile LaTeX document into a PDF

cd ../new/

# Generate EPUB
pandoc print.tex -o print.epub --metadata title="Martin Luther, His Life and Work" --metadata author="Hartmann Grisar, S.J."
# Generate PDF
latexmk -pdf print.tex
# pdflatex ebook.tex
