#!/bin/sh
# Find and Replace Multiple Words at once using sed

find ../new/  -type f -name "*.tex" -exec sed -i -E \
-e 's/sententis/sententia/g' \
-e 's/mneque/nec/g' \
-e 's/spectremonks/spectre-monks/g' \
-e 's/sols/sola/g' \
{} +
